source "http://rubygems.org"	
source "http://gems.github.com"
gem "nokogiri"				
gem "hpricot"
gem "actionmailer"
gem "rack", "~>1.1"			
gem "rspec", :require => "spec"			
gem "rack-contrib"
gem "technicalpickles-jeweler"
